import { writeFileSync } from "fs";
import { resolve } from "path";
import { runAgentLoop } from "../../agent";
import { parseTimeSince } from "./time-parser";
import { parsePostmortemFlags } from "./flags";
import { collectPostmortemContext, formatPostmortemContext } from "./context";
import type { LLMProvider } from "../../providers/types";

const POSTMORTEM_PROMPT = (context: string) => `You are a senior site reliability engineer. Using only the data provided below, draft a concise incident postmortem in markdown. Use these exact sections:

## What Happened
## Likely Root Cause
## Contributing Factors
## Timeline
## Recommended Action Items

Be specific — reference container names, exit codes, commit hashes, and metric values from the data. Do not speculate beyond what the data supports.

${context}`;

export async function runPostmortem(rawArgs: string, provider: LLMProvider): Promise<void> {
  const args = rawArgs.trim() ? rawArgs.trim().split(/\s+/) : [];
  const flags = parsePostmortemFlags(args);

  // Validate --since
  let since: string | undefined;
  if (flags.since) {
    const parsed = parseTimeSince(flags.since);
    if (!parsed) {
      throw new Error(`Invalid --since value "${flags.since}". Use formats like 30m, 2h, 1d, or an ISO timestamp.`);
    }
    since = parsed;
  }

  const target = flags.container;
  const outputFile = flags.output;

  process.stdout.write(
    `Collecting incident context${target ? ` for container: ${target}` : ""}${since ? ` since ${since}` : ""}...\n\n`
  );

  const ctx = await collectPostmortemContext(target, since);
  const contextBlock = formatPostmortemContext(ctx);

  process.stdout.write(`[${provider.name}] drafting postmortem...\n\n`);

  const postmortem = await runAgentLoop(
    provider,
    [{ role: "user", content: POSTMORTEM_PROMPT(contextBlock) }],
    {
      system: "You are a senior SRE. Draft postmortems that are blameless, factual, and actionable.",
      maxIterations: 1,
    }
  );

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const header = `# Incident Postmortem\n_Generated by Cael at ${ctx.timestamp}_\n\n`;
  const output = header + postmortem;

  if (outputFile) {
    const resolvedOutput = resolve(outputFile);
    const cwd = process.cwd();
    if (resolvedOutput !== cwd && !resolvedOutput.startsWith(cwd + "/")) {
      throw new Error(`Output path must be within the working directory`);
    }
    writeFileSync(resolvedOutput, output, "utf-8");
    console.log(postmortem);
    console.log(`\n---\nSaved to ${outputFile}`);
  } else {
    console.log(output);
  }
}
