import { resolve } from "path";
import { runAgentLoop } from "../../agent";
import { parseTimeSince } from "./time-parser";
import { parsePostmortemFlags } from "./flags";
import { collectPostmortemContext, formatPostmortemContext } from "./context";
import { extractTimeline, formatTimeline } from "./timeline";
import { DEFAULT_TEMPLATE } from "./default-template";
import type { LLMProvider } from "../../providers/types";

const MAX_TEMPLATE_BYTES = 50 * 1024; // 50KB

async function resolveTemplate(flagPath?: string): Promise<string> {
  // 1. --template flag (absolute or CWD-relative)
  if (flagPath) {
    const file = Bun.file(flagPath);
    try {
      if (file.size > MAX_TEMPLATE_BYTES) {
        process.stderr.write("Warning: --template file exceeds 50KB; using default template.\n");
        return DEFAULT_TEMPLATE;
      }
      return await file.text();
    } catch {
      process.stderr.write("Warning: could not read --template file; using default template.\n");
      return DEFAULT_TEMPLATE;
    }
  }

  // 2. .cael/postmortem-template.md in CWD
  const projectTemplate = Bun.file(".cael/postmortem-template.md");
  if (await projectTemplate.exists()) {
    try {
      if (projectTemplate.size <= MAX_TEMPLATE_BYTES) return await projectTemplate.text();
    } catch {}
  }

  // 3. Built-in default
  return DEFAULT_TEMPLATE;
}

const POSTMORTEM_PROMPT = (template: string, timeline: string, context: string) =>
  `You are a senior site reliability engineer. Using only the data provided below, draft a concise incident postmortem in markdown. Fill in each section defined in the template below — preserve the section headers exactly as written.

${timeline ? `## Pre-sorted Incident Timeline\n\n${timeline}\n\n---\n\n` : ""}TEMPLATE TO FILL IN:
${template}

---
INCIDENT DATA:
${context}`;

export async function runPostmortem(args: string[], provider: LLMProvider): Promise<void> {
  const flags = parsePostmortemFlags(args);

  let since: string | undefined;
  if (flags.since) {
    const parsed = parseTimeSince(flags.since);
    if (!parsed) {
      throw new Error(`Invalid --since value "${flags.since}". Use formats like 30m, 2h, 1d, or an ISO timestamp.`);
    }
    since = parsed;
  }

  const target = flags.container;
  const outputFile = flags.output;

  process.stdout.write(
    `Collecting incident context${target ? ` for container: ${target}` : ""}${since ? ` since ${since}` : ""}...\n\n`
  );

  const [ctx, template] = await Promise.all([
    collectPostmortemContext(target, since),
    resolveTemplate(flags.template),
  ]);

  const events = extractTimeline(ctx);
  const timelineTable = formatTimeline(events);
  const contextBlock = formatPostmortemContext(ctx);

  process.stdout.write(`[${provider.name}] drafting postmortem...\n\n`);

  const postmortem = await runAgentLoop(
    provider,
    [{ role: "user", content: POSTMORTEM_PROMPT(template, timelineTable, contextBlock) }],
    {
      system: "You are a senior SRE. Draft postmortems that are blameless, factual, and actionable.",
      maxIterations: 1,
    }
  );

  const header = `# Incident Postmortem\n_Generated by Cael at ${ctx.timestamp}_\n\n`;
  const output = header + postmortem;

  if (outputFile) {
    const resolvedOutput = resolve(outputFile);
    const cwd = process.cwd();
    if (resolvedOutput !== cwd && !resolvedOutput.startsWith(cwd + "/")) {
      throw new Error(`Output path must be within the working directory`);
    }
    await Bun.write(resolvedOutput, output);
    console.log(postmortem);
    console.log(`\n---\nSaved to ${outputFile}`);
  } else {
    console.log(output);
  }
}
